version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cmftool
  - composables
  - divs
  - favicons
  - heroicons
  - hugeicons
  - iconify
  - jschema
  - niemopen
  - nuxt
  - nuxtjs
  - octicon
  - persistedstate
  - pinia
  - pwa
  - Slideover
  - tabler
  - tailwindcss
  - ui
  - Vite
  - vueuse
ignoreWords: []
import: []
